name: commit to label
on: 
  issue_comment:
    types: [created, edited]

jobs:
  merge:
    if: contains(github.event.comment.html_url, '/pull/')
    
    runs-on: ubuntu-latest
    steps:
      - name: labelcommit
        # uses: 0daryo/labelcommit@main
        # specifying prebuilt docker image is faster.
        uses: docker://0daryo/labelcommit:latest
        with: 
          "github token": ${{ secrets.GITHUB_TOKEN }}
          "owner": "0daryo"
          "repo": "labelcommit"
          "pr number": ${{ github.event.issue.number }}
          "comment": ${{ github.event.comment.body }}
        
